[package]
name = "move-registry"
version = "0.1.0"
description = "MoveRegistry Anchor program for Krump move NFTs"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "move_registry"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = ["solana-program/no-entrypoint"]
no-idl = []
no-log-ix-name = []
cpi-no-idl = []
library = []

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
solana-program = "2.0"
mpl-token-metadata = "2.1"
